### PR TITLE
Feature/ticket 5/uml diagram first version

### PR DESCRIPTION
**Pull request by luiggy-mamani-jalafund**
# US 5 - UML Diagram - First version
[Link to US](https://trello.com/c/QYoz3Par/19-us-5-uml-diagram-version-1)
rPbVZzis3C3VxrC8VKgsNj_sLXHDxxAhWUiVNDC1UrHjrXLgou4ajnTqzzrNcOuLCtJe8KMtzUKiwaTH91NQOf_xe5rewqgjxxTWFMoSpZ-3KvVgnZNjzhUBY-rtWIv1FRf-ysgLlLQtgp_NTu_KjuiBfPGQPjSsc630nndL_pCsWFkeSr3TxEw5ze3JmxzVRrfJgAmOX0yNmsDUQU_LUmzEcNfRGGqs-1DB-U2CBTLhNGCxiQwrgTYPjz

### CODE REVIEW

**Comment by samuel-escalera-jalafund** [comment]
What is the part of the datasources??, I need this part in de UML for my US

**Comment by luiggy-mamani-jalafund** [comment]
> What is the part of the datasources??, I need this part in de UML for my US

Is this right? because I still think that we would be repeating code, I mean, If we wanna have another database for an specific repository, we could just create another concrete repository like _"MongoDbUserRepository"_
```
        interface IDataAccess<T implements EntityBase> {
            +bool Save(T item)
            +bool Update(T item)
            +bool Delete(T item)
            +T GetById(Guid itemId)
            +List<T> GetAll()
        }

        interface IUserDataAccess extends IDataAccess<User> {
            +User GetByEmail(string email)
        }

        interface IRepository<T implements EntityBase> {
            +bool Save(T item)
            +bool Update(T item)
            +bool Delete(T item)
            +T GetById(Guid itemId)
            +List<T> GetAll()
        }

        interface IUserRepository extends IRepository<User> {
            - IUserDataAccess userDataAccess

            +User GetByEmail(string email)
        }

        IUserRepository *-- IExpenseRepository
```

**Review by SebasthianSalpozz — COMMENTED** [review]
I thinks that is better to delete the validation becasue the trainer says that is not really important to do or what do you think @luiggy-mamani-jalafund

**Comment by luiggy-mamani-jalafund** [comment]
> I thinks that is better to delete the validation becasue the trainer says that is not really important to do or what do you think @luiggy-mamani-jalafund

yeah, he said isn't necessary to delete it tho

**Comment by samuel-escalera-jalafund** [comment]
> > What is the part of the datasources??, I need this part in de UML for my US
> 
> Is this right? because I still think that we would be repeating code, I mean, If we wanna have another database for an specific repository, we could just create another concrete repository like _"MongoDbUserRepository"_
> 
> ```
>         interface IDataAccess<T implements EntityBase> {
>             +bool Save(T item)
>             +bool Update(T item)
>             +bool Delete(T item)
>             +T GetById(Guid itemId)
>             +List<T> GetAll()
>         }
> 
>         interface IUserDataAccess extends IDataAccess<User> {
>             +User GetByEmail(string email)
>         }
> 
>         interface IRepository<T implements EntityBase> {
>             +bool Save(T item)
>             +bool Update(T item)
>             +bool Delete(T item)
>             +T GetById(Guid itemId)
>             +List<T> GetAll()
>         }
> 
>         interface IUserRepository extends IRepository<User> {
>             - IUserDataAccess userDataAccess
> 
>             +User GetByEmail(string email)
>         }
> 
>         IUserRepository *-- IExpenseRepository
> ```

“If we only use repositories (implementing the endpoints and the database access logic directly in them) and in the future we have to change the database, we would have to change **everywhere where that repository is used**, since each repository would be directly coupled to a specific database technology.

On the other hand, if a pattern with repository and datasource is applied, the repository only defines the domain operations (create, update, delete, etc.) and delegates to the datasource the specific implementation of database access. This way, if the database is changed in the future, only the implementation of the datasource used by the repository has to be changed, without touching any of the code in the rest of the project. This way, the business code remains independent of the persistence technology, which is one of the goals of DDD.”

https://www.paradigmadigital.com/techbiz/domain-driven-design-y-arquitectura-onion/

**Anyway, let's stick to using only repository for this project, taking into account that it is only a 2 week project.**

**Comment by samuel-escalera-jalafund** [comment]
> I thinks that is better to delete the validation becasue the trainer says that is not really important to do or what do you think @luiggy-mamani-jalafund

I agree with @SebasthianSalpozz , although the trainer mentioned that it is not necessary to eliminate our validators if we have already done them, he also mentioned that he was going to tell us later how the validators would be. Better to wait for the trainer to tell us how he wants the validators and delete the validators, at least for this first version of UML.

**Review by samuel-escalera-jalafund — CHANGES_REQUESTED** [review]
@luiggy-mamani-jalafund 
In general, let's keep the use of repositories only, and eliminate the validator. After that I have no further observations

**Comment by luiggy-mamani-jalafund** [comment]
> “If we only use repositories (implementing the endpoints and the database access logic directly in them) and in the future we have to change the database, we would have to change **everywhere where that repository is used**, since each repository would be directly coupled to a specific database technology.
> 
> On the other hand, if a pattern with repository and datasource is applied, the repository only defines the domain operations (create, update, delete, etc.) and delegates to the datasource the specific implementation of database access. This way, if the database is changed in the future, only the implementation of the datasource used by the repository has to be changed, without touching any of the code in the rest of the project. This way, the business code remains independent of the persistence technology, which is one of the goals of DDD.”
> 
> https://www.paradigmadigital.com/techbiz/domain-driven-design-y-arquitectura-onion/
> 
> **Anyway, let's stick to using only repository for this project, taking into account that it is only a 2 week project.**

so, you wanna use the concrete implementation of repositories? because I've thinking use the signatures or interfaces, and use dependency injection to use concrete implementation. With this approach we will not have to change anything in the implemented code if we want to "change databases for one or more repositories" because we are working based on the signature of the repository (Domain Layer)

**Comment by samuel-escalera-jalafund** [comment]
> > “If we only use repositories (implementing the endpoints and the database access logic directly in them) and in the future we have to change the database, we would have to change **everywhere where that repository is used**, since each repository would be directly coupled to a specific database technology.
> > On the other hand, if a pattern with repository and datasource is applied, the repository only defines the domain operations (create, update, delete, etc.) and delegates to the datasource the specific implementation of database access. This way, if the database is changed in the future, only the implementation of the datasource used by the repository has to be changed, without touching any of the code in the rest of the project. This way, the business code remains independent of the persistence technology, which is one of the goals of DDD.”
> > https://www.paradigmadigital.com/techbiz/domain-driven-design-y-arquitectura-onion/
> > **Anyway, let's stick to using only repository for this project, taking into account that it is only a 2 week project.**
> 
> so, you wanna use the concrete implementation of repositories? because I've thinking use the signatures or interfaces, and use dependency injection to use concrete implementation. With this approach we will not have to change anything in the implemented code if we want to "change databases for one or more repositories" because we are working based on the signature of the repository (Domain Layer)



> > “If we only use repositories (implementing the endpoints and the database access logic directly in them) and in the future we have to change the database, we would have to change **everywhere where that repository is used**, since each repository would be directly coupled to a specific database technology.
> > On the other hand, if a pattern with repository and datasource is applied, the repository only defines the domain operations (create, update, delete, etc.) and delegates to the datasource the specific implementation of database access. This way, if the database is changed in the future, only the implementation of the datasource used by the repository has to be changed, without touching any of the code in the rest of the project. This way, the business code remains independent of the persistence technology, which is one of the goals of DDD.”
> > https://www.paradigmadigital.com/techbiz/domain-driven-design-y-arquitectura-onion/
> > **Anyway, let's stick to using only repository for this project, taking into account that it is only a 2 week project.**
> 
> so, you wanna use the concrete implementation of repositories? because I've thinking use the signatures or interfaces, and use dependency injection to use concrete implementation. With this approach we will not have to change anything in the implemented code if we want to "change databases for one or more repositories" because we are working based on the signature of the repository (Domain Layer)

Really no, I think the current UML is good for this type of project, good job

**Review by samuel-escalera-jalafund — APPROVED** [review]

**Pull request closed without merging**
